---
version: '2'
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: always
    ports:
      - 8090:8080
      - 50001:50000
    volumes:
      - ./jenkins_home:/var/jenkins_home